package chi.pojo;
// Generated May 2, 2019 5:10:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private String customerId;
     private Users users;
     private String customerName;
     private String customerEmail;
     private String customerPhone;
     private String customerAddress;
     private String createdDate;
     private Set orderses = new HashSet(0);

    public Customers() {
    }

	
    public Customers(String customerId) {
        this.customerId = customerId;
    }
    public Customers(String customerId, Users users, String customerName, String customerEmail, String customerPhone, String customerAddress, String createdDate, Set orderses) {
       this.customerId = customerId;
       this.users = users;
       this.customerName = customerName;
       this.customerEmail = customerEmail;
       this.customerPhone = customerPhone;
       this.customerAddress = customerAddress;
       this.createdDate = createdDate;
       this.orderses = orderses;
    }
   
    public String getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerEmail() {
        return this.customerEmail;
    }
    
    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }
    public String getCustomerPhone() {
        return this.customerPhone;
    }
    
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public Set getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set orderses) {
        this.orderses = orderses;
    }




}


