package chi.pojo;
// Generated May 2, 2019 5:10:39 PM by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private String orderId;
     private Customers customers;
     private String orderName;
     private Double orderUnitPrice;
     private Integer orderQuantity;
     private Double orderTotalPrice;
     private String createdDate;

    public Orders() {
    }

	
    public Orders(String orderId) {
        this.orderId = orderId;
    }
    public Orders(String orderId, Customers customers, String orderName, Double orderUnitPrice, Integer orderQuantity, Double orderTotalPrice, String createdDate) {
       this.orderId = orderId;
       this.customers = customers;
       this.orderName = orderName;
       this.orderUnitPrice = orderUnitPrice;
       this.orderQuantity = orderQuantity;
       this.orderTotalPrice = orderTotalPrice;
       this.createdDate = createdDate;
    }
   
    public String getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }
    public String getOrderName() {
        return this.orderName;
    }
    
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }
    public Double getOrderUnitPrice() {
        return this.orderUnitPrice;
    }
    
    public void setOrderUnitPrice(Double orderUnitPrice) {
        this.orderUnitPrice = orderUnitPrice;
    }
    public Integer getOrderQuantity() {
        return this.orderQuantity;
    }
    
    public void setOrderQuantity(Integer orderQuantity) {
        this.orderQuantity = orderQuantity;
    }
    public Double getOrderTotalPrice() {
        return this.orderTotalPrice;
    }
    
    public void setOrderTotalPrice(Double orderTotalPrice) {
        this.orderTotalPrice = orderTotalPrice;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


