package chi.pojo;
// Generated May 2, 2019 5:10:39 PM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String productId;
     private Suppliers suppliers;
     private String productName;
     private Integer nafdacNumber;
     private Double unitPrice;
     private Integer quantity;
     private Double totalPrice;
     private String manufacturedDate;
     private String expireDate;
     private String createdDate;

    public Product() {
    }

	
    public Product(String productId) {
        this.productId = productId;
    }
    public Product(String productId, Suppliers suppliers, String productName, Integer nafdacNumber, Double unitPrice, Integer quantity, Double totalPrice, String manufacturedDate, String expireDate, String createdDate) {
       this.productId = productId;
       this.suppliers = suppliers;
       this.productName = productName;
       this.nafdacNumber = nafdacNumber;
       this.unitPrice = unitPrice;
       this.quantity = quantity;
       this.totalPrice = totalPrice;
       this.manufacturedDate = manufacturedDate;
       this.expireDate = expireDate;
       this.createdDate = createdDate;
    }
   
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public Suppliers getSuppliers() {
        return this.suppliers;
    }
    
    public void setSuppliers(Suppliers suppliers) {
        this.suppliers = suppliers;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Integer getNafdacNumber() {
        return this.nafdacNumber;
    }
    
    public void setNafdacNumber(Integer nafdacNumber) {
        this.nafdacNumber = nafdacNumber;
    }
    public Double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(Double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public String getManufacturedDate() {
        return this.manufacturedDate;
    }
    
    public void setManufacturedDate(String manufacturedDate) {
        this.manufacturedDate = manufacturedDate;
    }
    public String getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(String expireDate) {
        this.expireDate = expireDate;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }




}


