package chi.pojo;
// Generated May 2, 2019 5:10:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Suppliers generated by hbm2java
 */
public class Suppliers  implements java.io.Serializable {


     private String supplierId;
     private Users users;
     private String supplierName;
     private String supplierEmail;
     private String supplierPhone;
     private String companyName;
     private String createdDate;     
     private Set products = new HashSet(0);

    public Suppliers() {
    }

	
    public Suppliers(String supplierId) {
        this.supplierId = supplierId;
    }
    public Suppliers(String supplierId, Users users, String supplierName, String supplierEmail, String supplierPhone, String companyName, String createdDate, Set products) {
       this.supplierId = supplierId;
       this.users = users;
       this.supplierName = supplierName;
       this.supplierEmail = supplierEmail;
       this.supplierPhone = supplierPhone;
       this.companyName = companyName;
       this.createdDate = createdDate;
       this.products = products;
    }
   
    public String getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getSupplierName() {
        return this.supplierName;
    }
    
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName;
    }
    public String getSupplierEmail() {
        return this.supplierEmail;
    }
    
    public void setSupplierEmail(String supplierEmail) {
        this.supplierEmail = supplierEmail;
    }
    public String getSupplierPhone() {
        return this.supplierPhone;
    }
    
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public Set getProducts() {
        return this.products;
    }
    
    public void setProducts(Set products) {
        this.products = products;
    }




}


