package chi.pojo;
// Generated May 2, 2019 5:10:39 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {
    

     private String email;
     private String firstName;
     private String lastName;
     private String passwords;
     private String phone;
     private String position;
     private String createdDate;
     private Set customerses = new HashSet(0);
     private Set supplierses = new HashSet(0);

    public Users() {
    }
	
    public Users(String email) {
        this.email = email;
    }
    public Users(String email, String firstName, String lastName, String passwords, String phone, String position, String createdDate, Set customerses, Set supplierses) {
       this.email = email;
       this.firstName = firstName;
       this.lastName = lastName;
       this.passwords = passwords;
       this.phone = phone;
       this.position = position;
       this.createdDate = createdDate;
       this.customerses = customerses;
       this.supplierses = supplierses;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPasswords() {
        return this.passwords;
    }
    
    public void setPasswords(String passwords) {
        this.passwords = passwords;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getPosition() {
        return this.position;
    }
    
    public void setPosition(String position) {
        this.position = position;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public Set getCustomerses() {
        return this.customerses;
    }
    
    public void setCustomerses(Set customerses) {
        this.customerses = customerses;
    }
    public Set getSupplierses() {
        return this.supplierses;
    }
    
    public void setSupplierses(Set supplierses) {
        this.supplierses = supplierses;
    }




}


